version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
  pre_build:
    commands:
      - echo "Preparing environment..."
  build:
    commands:
      - echo "Building the project..."
  post_build:
    commands:
      - echo "Starting post-build activities..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
